# appspec.yml

version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/app/dist/dear-world-production
    overwrite: yes

permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user

hooks:
  ApplicationStart:
    - location: scripts/install_dependencies.sh
      timeout: 180
      runas: ec2-user
    - location: scripts/restart_server.sh
      timeout: 10
      runas: ec2-user
    - location: scripts/validate_server.sh
      timeout: 30
      runas: ec2-user